effects:
  opacity:
    values:
      - name: "0"
        value: "0"
      - name: "5"
        value: "0.05"
      - name: "10"
        value: "0.1"
      - name: "20"
        value: "0.2"
      - name: "25"
        value: "0.25"
      - name: "30"
        value: "0.3"
      - name: "40"
        value: "0.4"
      - name: "50"
        value: "0.5"
      - name: "60"
        value: "0.6"
      - name: "70"
        value: "0.7"
      - name: "75"
        value: "0.75"
      - name: "80"
        value: "0.8"
      - name: "90"
        value: "0.9"
      - name: "95"
        value: "0.95"
      - name: "100"
        value: "1"
  shadow:
    values:
      - name: "sm"
        value: "0 1px 2px 0 rgb(0 0 0 / 0.05)"
      - name: ""
        value: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)"
      - name: "md"
        value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)"
      - name: "lg"
        value: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)"
      - name: "xl"
        value: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)"
      - name: "2xl"
        value: "0 25px 50px -12px rgb(0 0 0 / 0.25)"
      - name: "inner"
        value: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)"
      - name: "none"
        value: "0 0 #0000"
  cursor:
    values:
      - name: "cursor-auto"
        css_property: "cursor: auto"
      - name: "cursor-default"
        css_property: "cursor: default"
      - name: "cursor-pointer"
        css_property: "cursor: pointer"
      - name: "cursor-wait"
        css_property: "cursor: wait"
      - name: "cursor-text"
        css_property: "cursor: text"
      - name: "cursor-move"
        css_property: "cursor: move"
      - name: "cursor-help"
        css_property: "cursor: help"
      - name: "cursor-not-allowed"
        css_property: "cursor: not-allowed"
      - name: "cursor-none"
        css_property: "cursor: none"
      - name: "cursor-context-menu"
        css_property: "cursor: context-menu"
      - name: "cursor-progress"
        css_property: "cursor: progress"
      - name: "cursor-cell"
        css_property: "cursor: cell"
      - name: "cursor-crosshair"
        css_property: "cursor: crosshair"
      - name: "cursor-vertical-text"
        css_property: "cursor: vertical-text"
      - name: "cursor-alias"
        css_property: "cursor: alias"
      - name: "cursor-copy"
        css_property: "cursor: copy"
      - name: "cursor-no-drop"
        css_property: "cursor: no-drop"
      - name: "cursor-grab"
        css_property: "cursor: grab"
      - name: "cursor-grabbing"
        css_property: "cursor: grabbing"
  user_select:
    values:
      - name: "select-none"
        css_property: "user-select: none"
      - name: "select-text"
        css_property: "user-select: text"
      - name: "select-all"
        css_property: "user-select: all"
      - name: "select-auto"
        css_property: "user-select: auto"
  pointer_events:
    values:
      - name: "pointer-events-none"
        css_property: "pointer-events: none"
      - name: "pointer-events-auto"
        css_property: "pointer-events: auto"
  visibility:
    values:
      - name: "visible"
        css_property: "visibility: visible"
      - name: "invisible"
        css_property: "visibility: hidden"
      - name: "collapse"
        css_property: "visibility: collapse"
  screen_readers:
    values:
      - name: "sr-only"
        css_property: "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border-width: 0"
      - name: "not-sr-only"
        css_property: "position: static; width: auto; height: auto; padding: 0; margin: 0; overflow: visible; clip: auto; white-space: normal"
  pseudo_classes:
    - hover
    - focus
    - active
    - disabled
    - visited