position:
  types:
    - name: "static"
      css_property: "position: static"
    - name: "fixed"
      css_property: "position: fixed"
    - name: "absolute"
      css_property: "position: absolute"
    - name: "relative"
      css_property: "position: relative"
    - name: "sticky"
      css_property: "position: sticky"
  inset:
    scale:
      - name: "0"
        value: "0"
      - name: "px"
        value: "1px"
      - name: "0.5"
        value: "0.125rem"
      - name: "1"
        value: "0.25rem"
      - name: "1.5"
        value: "0.375rem"
      - name: "2"
        value: "0.5rem"
      - name: "2.5"
        value: "0.625rem"
      - name: "3"
        value: "0.75rem"
      - name: "3.5"
        value: "0.875rem"
      - name: "4"
        value: "1rem"
      - name: "5"
        value: "1.25rem"
      - name: "6"
        value: "1.5rem"
      - name: "7"
        value: "1.75rem"
      - name: "8"
        value: "2rem"
      - name: "9"
        value: "2.25rem"
      - name: "10"
        value: "2.5rem"
      - name: "11"
        value: "2.75rem"
      - name: "12"
        value: "3rem"
      - name: "14"
        value: "3.5rem"
      - name: "16"
        value: "4rem"
      - name: "20"
        value: "5rem"
      - name: "24"
        value: "6rem"
      - name: "28"
        value: "7rem"
      - name: "32"
        value: "8rem"
      - name: "36"
        value: "9rem"
      - name: "40"
        value: "10rem"
      - name: "44"
        value: "11rem"
      - name: "48"
        value: "12rem"
      - name: "52"
        value: "13rem"
      - name: "56"
        value: "14rem"
      - name: "60"
        value: "15rem"
      - name: "64"
        value: "16rem"
      - name: "72"
        value: "18rem"
      - name: "80"
        value: "20rem"
      - name: "96"
        value: "24rem"
    special:
      - name: "auto"
        value: "auto"
      - name: "full"
        value: "100%"
      - name: "1/2"
        value: "50%"
      - name: "1/3"
        value: "33.333333%"
      - name: "2/3"
        value: "66.666667%"
      - name: "1/4"
        value: "25%"
      - name: "2/4"
        value: "50%"
      - name: "3/4"
        value: "75%"
    negative_scale:
      - name: "-px"
        value: "-1px"
      - name: "-0.5"
        value: "-0.125rem"
      - name: "-1"
        value: "-0.25rem"
      - name: "-1.5"
        value: "-0.375rem"
      - name: "-2"
        value: "-0.5rem"
      - name: "-2.5"
        value: "-0.625rem"
      - name: "-3"
        value: "-0.75rem"
      - name: "-3.5"
        value: "-0.875rem"
      - name: "-4"
        value: "-1rem"
      - name: "-5"
        value: "-1.25rem"
      - name: "-6"
        value: "-1.5rem"
      - name: "-7"
        value: "-1.75rem"
      - name: "-8"
        value: "-2rem"
      - name: "-9"
        value: "-2.25rem"
      - name: "-10"
        value: "-2.5rem"
      - name: "-11"
        value: "-2.75rem"
      - name: "-12"
        value: "-3rem"
      - name: "-14"
        value: "-3.5rem"
      - name: "-16"
        value: "-4rem"
      - name: "-20"
        value: "-5rem"
      - name: "-24"
        value: "-6rem"
      - name: "-28"
        value: "-7rem"
      - name: "-32"
        value: "-8rem"
      - name: "-36"
        value: "-9rem"
      - name: "-40"
        value: "-10rem"
      - name: "-44"
        value: "-11rem"
      - name: "-48"
        value: "-12rem"
      - name: "-52"
        value: "-13rem"
      - name: "-56"
        value: "-14rem"
      - name: "-60"
        value: "-15rem"
      - name: "-64"
        value: "-16rem"
      - name: "-72"
        value: "-18rem"
      - name: "-80"
        value: "-20rem"
      - name: "-96"
        value: "-24rem"
    negative_special:
      - name: "-full"
        value: "-100%"
      - name: "-1/2"
        value: "-50%"
      - name: "-1/3"
        value: "-33.333333%"
      - name: "-2/3"
        value: "-66.666667%"
      - name: "-1/4"
        value: "-25%"
      - name: "-2/4"
        value: "-50%"
      - name: "-3/4"
        value: "-75%"
  z_index:
    values:
      - name: "0"
        value: "0"
      - name: "10"
        value: "10"
      - name: "20"
        value: "20"
      - name: "30"
        value: "30"
      - name: "40"
        value: "40"
      - name: "50"
        value: "50"
      - name: "auto"
        value: "auto"
    negative_values:
      - name: "-10"
        value: "-10"
  overflow:
    types:
      - name: "overflow-auto"
        css_property: "overflow: auto"
      - name: "overflow-hidden"
        css_property: "overflow: hidden"
      - name: "overflow-visible"
        css_property: "overflow: visible"
      - name: "overflow-scroll"
        css_property: "overflow: scroll"
      - name: "overflow-x-auto"
        css_property: "overflow-x: auto"
      - name: "overflow-x-hidden"
        css_property: "overflow-x: hidden"
      - name: "overflow-x-visible"
        css_property: "overflow-x: visible"
      - name: "overflow-x-scroll"
        css_property: "overflow-x: scroll"
      - name: "overflow-y-auto"
        css_property: "overflow-y: auto"
      - name: "overflow-y-hidden"
        css_property: "overflow-y: hidden"
      - name: "overflow-y-visible"
        css_property: "overflow-y: visible"
      - name: "overflow-y-scroll"
        css_property: "overflow-y: scroll"