spacing:
  scale: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 72, 80, 96]
  rem_multiplier: 0.25
  properties:
    - name: padding
      prefix: p
      css_property: "padding: {value}"
    - name: padding-x
      prefix: px  
      css_property: "padding-left: {value}; padding-right: {value}"
    - name: padding-y
      prefix: py
      css_property: "padding-top: {value}; padding-bottom: {value}"
    - name: padding-top
      prefix: pt
      css_property: "padding-top: {value}"
    - name: padding-right
      prefix: pr
      css_property: "padding-right: {value}"
    - name: padding-bottom
      prefix: pb
      css_property: "padding-bottom: {value}"
    - name: padding-left
      prefix: pl
      css_property: "padding-left: {value}"
    - name: margin
      prefix: m
      css_property: "margin: {value}"
    - name: margin-x
      prefix: mx
      css_property: "margin-left: {value}; margin-right: {value}"
    - name: margin-y
      prefix: my
      css_property: "margin-top: {value}; margin-bottom: {value}"
    - name: margin-top
      prefix: mt
      css_property: "margin-top: {value}"
    - name: margin-right
      prefix: mr
      css_property: "margin-right: {value}"
    - name: margin-bottom
      prefix: mb
      css_property: "margin-bottom: {value}"
    - name: margin-left
      prefix: ml
      css_property: "margin-left: {value}"