typography:
  sizes:
    xs:
      size: "0.75rem"
      line_height: "1rem"
    sm:
      size: "0.875rem"
      line_height: "1.25rem"
    base:
      size: "1rem"
      line_height: "1.5rem"
    lg:
      size: "1.125rem"
      line_height: "1.75rem"
    xl:
      size: "1.25rem"
      line_height: "1.75rem"
    "2xl":
      size: "1.5rem"
      line_height: "2rem"
    "3xl":
      size: "1.875rem"
      line_height: "2.25rem"
    "4xl":
      size: "2.25rem"
      line_height: "2.5rem"
    "5xl":
      size: "3rem"
      line_height: "1"
    "6xl":
      size: "3.75rem"
      line_height: "1"
    "7xl":
      size: "4.5rem"
      line_height: "1"
    "8xl":
      size: "6rem"
      line_height: "1"
    "9xl":
      size: "8rem"
      line_height: "1"
  families:
    - name: font-sans
      css_property: "font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
    - name: font-serif
      css_property: "font-family: ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif"
    - name: font-mono
      css_property: "font-family: ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace"
  align:
    - name: text-left
      css_property: "text-align: left"
    - name: text-center
      css_property: "text-align: center"
    - name: text-right
      css_property: "text-align: right"
    - name: text-justify
      css_property: "text-align: justify"
  weight:
    - name: font-thin
      css_property: "font-weight: 100"
    - name: font-extralight
      css_property: "font-weight: 200"
    - name: font-light
      css_property: "font-weight: 300"
    - name: font-normal
      css_property: "font-weight: 400"
    - name: font-medium
      css_property: "font-weight: 500"
    - name: font-semibold
      css_property: "font-weight: 600"
    - name: font-bold
      css_property: "font-weight: 700"
    - name: font-extrabold
      css_property: "font-weight: 800"
    - name: font-black
      css_property: "font-weight: 900"
  decoration:
    - name: underline
      css_property: "text-decoration-line: underline"
    - name: overline
      css_property: "text-decoration-line: overline"
    - name: line-through
      css_property: "text-decoration-line: line-through"
    - name: no-underline
      css_property: "text-decoration-line: none"